server:
  port: 7080

management:
  server:
    port: 7081

leader-election:
  hazelcast-config-properties:
    hazelcast.discovery.enabled: 'true'
    hazelcast.initial.min.cluster.size: '3'
    hazelcast.phone.home.enabled: 'false'
    hazelcast.shutdownhook.policy: 'GRACEFUL'
  kubernetes-service-name: 'leader-election'
  leadership-poll-millis: 30000
  min-quorum-size: 2
