apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election
  labels:
    app: leader-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      containers:
        - image: vanillaslice/leader-election
          name: leader-election
          ports:
            - containerPort: 7080
            - containerPort: 7081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7081
            initialDelaySeconds: 300
