apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election
  labels:
    app: leader-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      containers:
        - image: vanillaslice/leader-election
          name: leader-election
          ports:
            - containerPort: 7080
          readinessProbe:
            httpGet:
              path: /ready
              port: 7080
