apiVersion: v1
kind: Service
metadata:
  name: leader-election
spec:
  selector:
    app: leader-election
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7080
    - name: hazelcast
      port: 5701
